#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Author Jan Löser <jloeser@suse.de>
# Published under the GNU Public Licence 2
# from bluebird import main
from bluebird import main

if __name__ == '__main__':
    main.run()
